version: "3.2"
services:
  django:
    build:
      context: .
      dockerfile: Dockerfile.python
    container_name: 'django_rabbitmq'
    ports:
      - "8000:8000"
    volumes:
      - .:/code
    environment:
      - CELERY_BROKER_URL=amqp://guest:guest@rabbitmq:5672//
      - CELERY_RESULT_BACKEND=django-db://sqlite:///db.sqlite3
      - CELERY_RESULT_DBURI=django-db://sqlite:///db.sqlite3
      - CELERY_CACHE_BACKEND=django-cache
    depends_on:
      - rabbitmq
    networks:
      - rabbitmq_go_net
  rabbitmq:
    build:
      context: .
      dockerfile: Dockerfile.rabbitmq
    container_name: 'rabbitmq'
    ports:
      - "5672:5672"
      - "15672:15672"
    volumes:
      - ~/.docker-conf/rabbitmq/data/:/var/lib/rabbitmq/
      - ~/.docker-conf/rabbitmq/log/:/var/log/rabbitmq
    networks:
      - rabbitmq_go_net

networks:
  rabbitmq_go_net:
    driver: bridge